name: manager
description: "yet another state management package"
publish_to: "none"
version: 3.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  states_rebuilder: ^6.4.0
  package_info_plus: ^8.1.1
  forui: ^0.9.0
  objectbox: ^4.1.0
  permission_handler: ^11.3.1
  hive_flutter: ^1.1.0
flutter:
  uses-material-design: true
