name: manager
description: "yet another dependency injection and architecture enforcement package plus navigation extensions"
publish_to: "none"
version: 4.0.2

environment:
    sdk: ^3.12.0
dependencies:
    flutter:
        sdk: flutter
flutter:
    uses-material-design: true
